name: ird
channels:
  - milaboratories
  - pytorch
  - svalkiers
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - asttokens=2.0.5
  - attr=2.5.1
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - biopython=1.81
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cachecontrol=0.12.11
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - clustalo=1.2.3
  - clustcr=1.0.2+17.gdb12543
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.11.0
  - cython=0.29.32
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.5.0
  - faiss=1.7.2
  - faiss-cpu=1.7.2
  - fastcluster=1.2.6
  - fftw=3.3.10
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.1
  - glib-tools=2.78.1
  - glpk=5.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gstreamer-orc=0.4.33
  - harfbuzz=8.3.0
  - hdmedians=0.14.2
  - icu=73.2
  - idna=3.4
  - igraph=0.10.3
  - importlib-metadata=4.11.3
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jack=1.9.22
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_console=6.4.4
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.5
  - jupyterlab_widgets=1.0.0
  - kaleido-core=0.2.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - leidenalg=0.9.1
  - lerc=3.0
  - levenshtein=0.20.9
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libfaiss=1.7.2
  - libfaiss-avx2=1.7.2
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.17
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=252
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvmlite=0.39.1
  - lockfile=0.12.2
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markov_clustering=0.0.6
  - markupsafe=2.1.1
  - mathjax=2.7.7
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - matplotlib-venn=0.11.9
  - metis=5.1.0
  - mistune=0.8.4
  - mixcr=4.5.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpfr=4.0.2
  - mpg123=1.31.2
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - mysql=5.7.20
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - natsort=7.1.1
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.88
  - numba=0.56.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openpyxl=3.0.10
  - openssl=3.2.1
  - packaging=22.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parmap=1.6.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - pixman=0.43.2
  - platformdirs=2.5.2
  - plotly=5.19.0
  - pluggy=1.0.0
  - ply=3.11
  - polars=0.15.14
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - py=1.11.0
  - pycairo=1.26.1
  - pycparser=2.21
  - pygments=2.11.2
  - pynndescent=0.5.10
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-igraph=0.10.4
  - python-kaleido=0.2.1
  - python-levenshtein=0.20.9
  - python-louvain=0.16
  - python_abi=3.9
  - pytz=2022.7
  - pyzmq=23.2.0
  - qt=5.15.9
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - rapidfuzz=2.13.7
  - readline=8.2
  - requests=2.28.1
  - scikit-bio=0.5.6
  - scikit-learn=1.2.2
  - scipy=1.8.0
  - seaborn=0.12.2
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - suitesparse=5.10.1
  - tbb=2021.9.0
  - tenacity=8.2.2
  - terminado=0.17.1
  - texttable=1.6.4
  - threadpoolctl=3.1.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - umap-learn=0.5.3
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - dill==0.3.6
      - feather-format==0.4.1
      - fisher==0.1.10
      - fishersapi==0.5
      - hierdiff==0.9
      - logomaker==0.8
      - networkx==3.0
      - olga==1.2.4
      - palmotif==0.4
      - parasail==1.3.3
      - progress==1.6
      - pwseqdist==0.6
      - pyarrow==11.0.0
      - pysankey==0.0.1
      - svgwrite==1.4.3
      - tcrsampler==0.1.9
      - zipdist==0.1.5
